### ISSUE TITLE
Add support for Lidarr

### ISSUE THREAD

**Issue by MrPetovan** [Morzomb/All-jellyfin-media-server#17]
First of all thank you for this project who might make the jump from streaming services to a hosted media library easier for me, however my main use case would be a music library. I saw this project includes a Sonarr and Radarr image for TV shows and movies respectively, how challenging would it be to add a Lidarr image to the mix?

**Comment by Morzomb** [comment]
Hello @MrPetovan , I don't think it would be more complicated to add a Lidarr in this setup. Especially since it would work perfectly with the other containers. I think that if I wanted to add a Lidarr, its configuration in the docker-compose would look like this:

```yaml
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:${COMMON_PATH}
      - ${COMMON_PATH}/configs/lidarr:/config
      - ${COMMON_PATH}/lidarr/music:/music
      - ${COMMON_PATH}/qbittorrent/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
```
If you have any more questions or need further assistance, feel free to ask. I hope you will enjoy it!
