### ISSUE TITLE
ProtonVPN [Closed]

### ISSUE THREAD

**Issue by Fudo7sei** [Morzomb/All-jellyfin-media-server#5]
Hi, is ProtonVPN compatible ? if yes, do i have to replace "nordvpn" by "protonvpn" in the yaml or not necessary ? There is more to do ?

**Comment by Fudo7sei** [comment]
additional question : what is this port 51420 ? what's his function ?

**Comment by Morzomb** [comment]
Hello @Fudo7sei 

Yes, it is possible to use Proton VPN in this tutorial. I use gluetun which manages a large number of VPN providers. [(Link to all available VPNs)](https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers)

To use Proton VPN, you must indeed change the .yaml file.

Here is an example:

```yml
  gluetun:
    image: qmcgaw/gluetun
    ports:
      - 8080:8080
      - 51420:51420
      - 51420:51420/udp
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=username
      - OPENVPN_PASSWORD=password
      - SERVER_COUNTRIES=Netherlands
```

You will find all other optional parameters on this [link](https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md)

As for your second question, port 51420 is the port that allows qbitorrents to access the internet to download, but the port is open on gluetun because it first passes through the VPN.

**Comment by Fudo7sei** [comment]
OK thanks you ! that's clear for me :) and thanks a lot for your work !

**Comment by Morzomb** [comment]
You're welcome! I'm glad I could help clarify things for you. If you have any more questions or need further assistance, feel free to ask. I hope you will enjoy it!

**Comment by Fudo7sei** [comment]
Yes, i just was wondering if i could install all your stuff except the jellyfin server bcs i already have one but not under docker, directly installed on my fedora server, you think it can work with your other containers or i have to make it work with your full solution ? I ask for radarr and sonarr (under docker) connection with my existant jellyfin.

**Comment by Morzomb** [comment]
Hello,

Yes, it is possible to use a Jellyfin that is already installed locally on your machine. To install without Jellyfin, you just need to remove the Jellyfin part from the **.yaml** file:

```yaml
  jellyfin:
    image:  lscr.io/linuxserver/jellyfin:latest
    container_name:  jellyfin
    environment:
      -  PUID=0
      -  PGID=0
      -  TZ=${TZ}
      -  NVIDIA_VISIBLE_DEVICES=all
    ports:
      -  8096:8096
      -  8920:8920
      -  7359:7359/udp
      -  1900:1900/udp
    volumes:
      - ${COMMON_PATH}:${COMMON_PATH}
      - ${COMMON_PATH}/configs/jellyfin:/config
      - ${COMMON_PATH}/jellyfin/cache:/cache
      - ${COMMON_PATH}/sonarr/tv:/data/tvshows
      - ${COMMON_PATH}/radarr/movies:/data/movies
      - ${COMMON_PATH}/qbittorrent/downloads:/data/media_downloads
    restart:  unless-stopped
```

However, you will need to make sure to create the necessary folders for movies and TV series, and you will also need to give your Jellyfin access to your movies and/or TV series.

Afterwards, it might be simpler to use the complete solution.
