### ISSUE TITLE
Issue with other applications connecting to qbittorrent

### ISSUE THREAD

**Issue by apotenza92** [Morzomb/All-jellyfin-media-server#6]
Hi, thanks for making this it's helped me (a noobie) figure a lot out!

I'm at the stage of trying to get sonarr to connect to qbittorrent as a download client but i keep getting an error.

I presume this is because qbittorrent is accessing the vpn (I'm using the vpn only config) while sonarr is not on the vpn network so the two cannot see each other?

Is this a flaw in your config file or am I doing something wrong.

![image](https://github.com/user-attachments/assets/d8ff0d54-c3a8-4ecf-80d7-0cde206f7d45)

**Comment by apotenza92** [comment]
OMG I think I just figured it out. I needed to put in the name of the container under 'Host' in sonarr as the name of the VPN container and it worked.

**Comment by Morzomb** [comment]
Hello, @apotenza92 

For my part, I did this simply by entering the IP that hosts my qbittorrent.

Example:
![image](https://github.com/user-attachments/assets/a17a49b9-899b-4675-856b-b966013da28f)

I recommend you do the same.

I will set up documentation for configuring the different Docker containers soon, if you think that would be helpful.

**Comment by apotenza92** [comment]
Thank you for the very fast response! Yeh I think that might be helpful for newbies like me.
One question I had for you was what do you think is the recommended way to sync my settings using the repo? At the moment I'm basically syncing my configs folder to github (and ignoring the database files because they get too big) is there a better way to do it I'm unaware of?

**Comment by Morzomb** [comment]
Hi,

To be honest with you, I didn't fully understand the problem you're facing with the sync. But i can show you how my system is structured:

![rep2](https://github.com/user-attachments/assets/3781adbf-c09a-42fd-87ae-aeeac309fe93)

1. **Content of "COMMON_PATH"**: Once Docker Compose is launched, the `COMMON_PATH` folder contains various subfolders for services like Jellyfin, Radarr, Sonarr, etc. This helps organize files and configurations properly (see section 1 of the image).

2. **Download folder**: All movies and series are initially downloaded to the `qbittorrent/downloads` directory (see section 2 of the image). This centralizes the initial download process.

3. **Movies destination**: After downloading, movies are automatically moved to the `radarr/movies` folder (see section 3 of the image). This helps keep media well-organized.

4. **Series destination**: Similarly, downloaded series are moved to the `sonarr/tv` folder (see section 4 of the image), allowing for consistent management like with movies.

Most of the configurations for these services can be accessed and adjusted through their respective web interfaces, making it easier to manage and fine-tune their settings.

Feel free to provide more details about your issue so I can assist you.

**Comment by Morzomb** [comment]
Hello @apotenza92,

Hope you’re doing well! Just wanted to let you know that I’ve updated the installation documentation and added a new configuration section. I hope this will help with any issues you’re facing. Let me know if you have any questions or need further assistance!

**Comment by akelshareif** [comment]
@Morzomb just chiming in here as another noob. What OS do you recommend using? Would this work with something like TruNas or should I go with linux like Ubuntu/Ubuntu Server/Debian?

**Comment by apotenza92** [comment]
@akelshareif I've been playing around with things for the last few weeks. For what it's worth, running off docker is relatively OS agnostic. Doesn't really matter too much what your OS is as long as it supports docker. I believe TruNAS has weird docker support with some upcoming releases supporting it? 

I'm considering CasaOS to run on a small Nas https://casaos.zimaspace.com/.

I may even delve into Proxmox as a base OS and run a Debian/Ubuntu VM on top of that instead.

**Comment by Morzomb** [comment]
Hi @akelshareif, 

TruNAS could be a good option since, if I remember correctly, it already includes Docker. That said, there's not necessarily one OS that's definitively better than another. My advice would be to choose an OS based on how easy it is to install and update NVIDIA drivers. Ultimately, go with what works best for you, but I’d recommend Ubuntu over Debian, even though my tutorial works on both.

**Comment by phillipdyb** [comment]
qBitTorrent does not expose 8080, so I'm unable to connect to it.
Same for WebUI and Client Connection in Sonarr.

**Comment by apotenza92** [comment]
If anyone needs help here's my currently working docker compose file. I've added a fair few more services than what is originally in this github. I would not recommend copying it all but take parts if you need it. Everything in ${} I'm keeping in a .env file so that I'm not storing anything hardcoded in the docker compose file.

```
networks:
  proxy_network:
    driver: bridge
  vpn_network:
    driver: bridge

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy_network
      - vpn_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api=true"
      - "--entrypoints.web.http.middlewares=rate-limit@docker"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.middlewares.auth.basicauth.users=${HASHED_PASSWORD}"
      - "traefik.http.routers.dashboard.middlewares=rate-limit@docker,security-headers@docker,auth@docker"
      - "traefik.http.middlewares.rate-limit.ratelimit.average=100"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=50"
      - "traefik.http.middlewares.security-headers.headers.framedeny=true"
      - "traefik.http.middlewares.security-headers.headers.browserxssfilter=true"

  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
      - MKNOD
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - vpn_network
      - proxy_network
    ports:
      - 8080:8080
      - 51420:51420
      - 51420:51420/udp
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - VPN_TYPE=openvpn
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.routers.qbittorrent.service=qbittorrent"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.qbittorrent-headers.headers.customRequestHeaders.Referer=http://qbittorrent.${DOMAIN}"
      - "traefik.http.middlewares.qbittorrent-headers.headers.customRequestHeaders.Origin=http://qbittorrent.${DOMAIN}"
      - "traefik.http.routers.qbittorrent.middlewares=rate-limit@docker,security-headers@docker,qbittorrent-headers@docker"
    depends_on:
      - traefik

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    depends_on:
      - vpn
      - traefik
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod
    volumes:
      - ${MEDIA_PATH}:/media
      - ${CONFIG_PATH}/qbittorrent:/config
    entrypoint: >
      /bin/sh -c " while ! curl -s https://ghcr.io > /dev/null; do
        echo 'Waiting for VPN connection...';
        sleep 1;
      done; /init"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - proxy_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - proxy_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - proxy_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - proxy_network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.${DOMAIN}`)"
      - "traefik.http.routers.flaresolverr.entrypoints=web"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
      - "traefik.http.routers.flaresolverr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      - proxy_network
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${MEDIA_PATH}/tv:/data/tvshows
      - ${MEDIA_PATH}/movies:/data/movies
      - ${MEDIA_PATH}/other-videos:/data/other-videos
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - proxy_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/overseerr:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN}`)"
      - "traefik.http.routers.overseerr.entrypoints=web"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.overseerr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik
      - plex

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - proxy_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${CONFIG_PATH}/jellyfin/cache:/cache
      - ${MEDIA_PATH}/tv:/data/tvshows
      - ${MEDIA_PATH}/movies:/data/movies
      - /usr/lib/jellyfin-ffmpeg:/shared/jellyfin-ffmpeg:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video

  mediaflow-proxy:
    container_name: mediaflow-proxy
    image: mhdzumair/mediaflow-proxy:latest
    networks:
      - proxy_network
    ports:
      - "8888:8888"
    environment:
      - API_PASSWORD=${TXT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - ALL_PROXY=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mediaflow.rule=Host(`mediaflow.${DOMAIN}`)"
      - "traefik.http.routers.mediaflow.entrypoints=web"
    depends_on:
      - traefik

  requestrr:
    container_name: requestrr
    image: thomst08/requestrr:latest
    networks:
      - proxy_network
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/requestrr:/root/config
    ports:
      - "4545:4545"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.requestrr.rule=Host(`requestrr.${DOMAIN}`)"
      - "traefik.http.routers.requestrr.entrypoints=web"
      - "traefik.http.services.requestrr.loadbalancer.server.port=4545"
      - "traefik.http.routers.requestrr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik
      - overseerr

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: ${PUID}:${PGID}
    networks: [ proxy_network ]
    volumes:
      - ${CONFIG_PATH}/recyclarr/config:/config
      - ./recyclarr.yml:/config/recyclarr.yml
      - ./recyclarr-anime.yml:/config/recyclarr-anime.yml
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - proxy_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN}`)"
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.http.routers.bazarr.middlewares=rate-limit@docker,security-headers@docker"
    depends_on:
      - traefik

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${GMAIL_APP_PASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=10
      - WATCHTOWER_RUN_ONCE=true

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - proxy_network
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      - PUID=${PUID}
      - PGID=${PGID}

  tailscale:
    container_name: tailscale
    hostname: tailscale-nas
    image: tailscale/tailscale:stable
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-routes=192.168.0.0/24 --accept-dns=true
      - TS_AUTH_KEY=${TAILSCALE_AUTH_KEY}
    volumes:
      - ${CONFIG_PATH}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    network_mode: "host"
    privileged: true
    restart: unless-stopped
```
